config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root  'static_pages#home'

  get 'users/new'

  get 'login'  => 'admin_page#new'
  post 'login'  => 'admin_page#create'
  get 'dashboard' => 'admin_page#dashboard'
  get 'logout' => 'admin_page#destroy'
  resource :users

  get 'admin_page/index'

  get 'admin_page/status'

  get 'static_pages/contact'

  get 'static_pages/portfolio'

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

end

app/controllers/admin_page_controller.rb
class AdminPageController < ApplicationController

  layout 'admin'
  before_action :logged_in_user, only: [:dashboard]

  def dashboard
  end

  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
# Log the user in and redirect to the user's show page.
      log_in user
      redirect_to dashboard_path

    else
# Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'

      render 'new'
    end
  end

  def destroy
    log_out
    reset_session

    redirect_to root_url
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include AdminPageHelper

  before_filter :set_no_cache

  def set_no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'admin'
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
# Log the user in and redirect to the user's show page.
      log_in user
      redirect_to dashboard_path

    else
# Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'

      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def portfolio
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/admin_page_helper.rb
module AdminPageHelper
  def full_title(page_title = '')                     # Method def, optional arg
    base_title = "Ruby on Rails Tutorial Sample App"  # Variable assignment
    if page_title.empty?                              # Boolean test
      base_title                                      # Implicit return
    else
      page_title + " | " + base_title                 # String concatenation
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])

  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])

  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_page/new.html.erb
<% provide(:title, "Log in") %>
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>



<div class="middle-box text-center loginscreen  animated fadeInDown">
  <div>
    <div>

      <h1 class="logo-name">IN+</h1>

    </div>
    <h3>Welcome to IN+</h3>
    <p>Perfectly designed and precisely prepared admin theme with over 50 pages with extra new web app views.
      <!--Continually expanded and constantly improved Inspinia Admin Them (IN+)-->
    </p>
    <p>Login in. To see it in action.</p>

    <%= form_for(:session, url: login_path, class:'m-t') do |f| %>
        <div class="form-group">
        <%= f.email_field :email, class: 'form-control', placeholder:'email' %>
        </div>
        <div class="form-group">
        <%= f.password_field :password, class: 'form-control', placeholder: 'password' %>
          </div>
        <%= f.submit "Log in", class: "btn btn-primary block full-width m-b" %>
    <% end %>

    <p class="m-t"> <small>Inspinia we app framework base on Bootstrap 3 &copy; 2014</small> </p>
  </div>
</div>

<!-- Mainly scripts -->
<script src="/assets/admin/js/jquery-1.10.2.js"></script>
<script src="/assets/admin/js/bootstrap.min.js"></script>

app/views/layouts/admin.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title><%= full_title(yield(:title)) %></title>

  <link href="/assets/admin/css/bootstrap.min.css" rel="stylesheet">
  <link href="/assets/admin/css/font-awesome/css/font-awesome.css" rel="stylesheet">

  <!-- Morris -->
  <link href="/assets/admin/css/plugins/morris/morris-0.4.3.min.css" rel="stylesheet">

  <!-- Gritter -->
  <link href="/assets/admin/js/plugins/gritter/jquery.gritter.css" rel="stylesheet">

  <link href="/assets/admin/css/animate.css" rel="stylesheet">
  <link href="/assets/admin/css/style.css" rel="stylesheet">
</head>
<body>
<%= yield %>

</body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/portfolio.html.erb
<h1>StaticPages#portfolio</h1>
<p>Find me in app/views/static_pages/portfolio.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>